CREATE TABLE RALUCA_P_ONLINE_CUSTOMER (
CUSTOMER_ID int not null,
FIRST_NAME varchar(50) not null,
LAST_NAME varchar(50) not null,
ADDRESS varchar(100) not null,
CONSTRAINT RALUCA_P_ONLINE_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE RALUCA_P_ONLINE_ITEM (
ITEM_CODE int not null,
DESCRIPTION varchar(150) not null,
PRICE numeric not null,
CATEGORY varchar(50) not null,
STOCK int not null,
CONSTRAINT RALUCA_P_ONLINE_ITEM_PK PRIMARY KEY (ITEM_CODE)
);


CREATE TABLE RALUCA_P_ONLINE_PAYMENT (
PAYMENT_ID int not null,
DATE date not null,
AMOUNT numeric not null,
TYPE varchar(50) not null,
CART_ID int not null,
CUSTOMER_ID int not null,
CONSTRAINT RALUCA_P_ONLINE_PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
);

	
CREATE TABLE RALUCA_P_ONLINE_SHOPPING_CART (
CART_ID int not null,
CUSTOMER_ID int not null,
DATE date not null,
ITEM_CODE int not null,
DESCRIPTION varchar(150) not null,
PRICE numeric not null,
CATEGORY varchar(50) not null,
CONSTRAINT RALUCA_P_ONLINE_SHOPPING_CART_PK PRIMARY KEY (CART_ID)
);

ALTER TABLE RALUCA_P_ONLINE_PAYMENT
ADD FOREIGN KEY (CART_ID) 
REFERENCES RALUCA_P_ONLINE_SHOPPING_CART(CART_ID);

ALTER TABLE RALUCA_P_ONLINE_PAYMENT
ADD FOREIGN KEY (CUSTOMER_ID) 
REFERENCES RALUCA_P_ONLINE_CUSTOMER(CUSTOMER_ID);

ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
ADD FOREIGN KEY (CUSTOMER_ID)
REFERENCES RALUCA_P_ONLINE_CUSTOMER(CUSTOMER_ID);

ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
ADD FOREIGN KEY (ITEM_CODE)
REFERENCES RALUCA_P_ONLINE_ITEM(ITEM_CODE);


SELECT * FROM RALUCA_P_ONLINE_CUSTOMER;
SELECT * FROM RALUCA_P_ONLINE_ITEM;
SET FOREIGN_KEY_CHECKS=1;

ALTER TABLE RALUCA_P_ONLINE_PAYMENT
DROP FOREIGN KEY CART_ID;
SELECT * FROM RALUCA_P_ONLINE_PAYMENT;
SELECT * FROM RALUCA_P_ONLINE_SHOPPING_CART;




DELETE FROM RALUCA_P_ONLINE_PAYMENT
WHERE PAYMENT_ID=1;
DELETE FROM RALUCA_P_ONLINE_PAYMENT
WHERE PAYMENT_ID=2;


DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=1;

DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=2;

SHOW CREATE TABLE RALUCA_P_ONLINE_SHOPPING_CART;

ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
drop primary key;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
DROP FOREIGN KEY RALUCA_P_ONLINE_SHOPPING_CART_ibfk_1;
ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
DROP FOREIGN KEY RALUCA_P_ONLINE_SHOPPING_CART_ibfk_2;

ALTER TABLE RALUCA_P_ONLINE_PAYMENT
DROP FOREIGN KEY RALUCA_P_ONLINE_PAYMENT_ibfk_1;
ALTER TABLE RALUCA_P_ONLINE_PAYMENT
DROP FOREIGN KEY RALUCA_P_ONLINE_PAYMENT_ibfk_2;

ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
drop primary key;

ALTER TABLE RALUCA_P_ONLINE_SHOPPING_CART
ADD CONSTRAINT PK_RALUCA_P_ONLINE_SHOPPING_CART PRIMARY KEY (CART_ID, ITEM_CODE);

SELECT * FROM RALUCA_P_ONLINE_SHOPPING_CART;
DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=1;
DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=2;


CREATE TABLE RALUCA_P_ONLINE_RECEIPT (
CART_ID int not null,
RECEIPT blob null,
AMOUNT numeric not null,
PAYMENT_TYPE varchar(50) not null,
ITEM_CATEGORY varchar(50) null,
CONSTRAINT RALUCA_P_ONLINE_RECEIPT_PK PRIMARY KEY (CART_ID)
);


SELECT * FROM RALUCA_P_ONLINE_RECEIPT;
SELECT RECEIPT
FROM RALUCA_P_ONLINE_RECEIPT
WHERE CART_ID=2;
DELETE 
FROM RALUCA_P_ONLINE_RECEIPT
WHERE CART_ID=1;
DELETE 
FROM RALUCA_P_ONLINE_RECEIPT
WHERE CART_ID=2;

SELECT * 
FROM RALUCA_P_ONLINE_ORDERED_ITEMS A
JOIN RALUCA_P_ONLINE_SHOPPING_CART B ON A.CART_ID=B.CART_ID
WHERE B.CART_ID=1;

SELECT * FROM RALUCA_P_ONLINE_SHOPPING_CART;
SELECT * FROM RALUCA_P_ONLINE_PAYMENT;

DELETE FROM RALUCA_P_ONLINE_PAYMENT
WHERE PAYMENT_ID=1;

DELETE FROM RALUCA_P_ONLINE_PAYMENT
WHERE PAYMENT_ID=2;

DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=1;

DELETE FROM RALUCA_P_ONLINE_SHOPPING_CART
WHERE CART_ID=2;

SELECT SUM(A.QUANTITY*A.PRICE)
FROM RALUCA_P_ONLINE_ORDERED_ITEMS A 
JOIN RALUCA_P_ONLINE_SHOPPING_CART B ON A.CART_ID=B.CART_ID
WHERE B.DATE='2018-10-19';



select NOW() FROM dual;

SELECT A.CATEGORY, SUM(A.QUANTITY*A.PRICE)
FROM RALUCA_P_ONLINE_ORDERED_ITEMS A 
JOIN RALUCA_P_ONLINE_SHOPPING_CART B ON A.CART_ID=B.CART_ID
GROUP BY A.CATEGORY;

ALTER TABLE RALUCA_P_PETS
ADD CONSTRAINT RALUCA_P_PETS_UNQ UNIQUE (NAME, BIRTHDATE);

DELETE FROM RALUCA_P_ONLINE_ITEM
WHERE ITEM_CODE=12;

SELECT * FROM RALUCA_P_ONLINE_CUSTOMER;
select * FROM RALUCA_P_ONLINE_STOCK_ITEM;
SELECT * FROM RALUCA_P_ONLINE_SHOPPING_CART;
SELECT * FROM RALUCA_P_ONLINE_ORDERED_ITEMS;
SELECT * FROM RALUCA_P_ONLINE_PAYMENT;
SELECT * FROM RALUCA_P_ONLINE_RECEIPT;


RENAME TABLE  RALUCA_P_ONLINE_ITEM TO  RALUCA_P_ONLINE_STOCK_ITEM;